### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by robertauer** [clintjedwards/dht22_exporter#2]
Hi!
Thank you so much for setting up this project, I really like it!
To make it more accessible for new users I have some small suggestions:
- Include "Adafruit_DHT" in the requirements.txt as it is required to run your python script
- Maybe change the first line of your script from `#!/usr/bin/env python` to `#!/usr/bin/env python3`. At least this did the trick for me, because the first time I ran it, it didn't know "prometheus_client" and failed.
- Maybe change the "and daemon-reload systemd" in your Readme to the actual command (`systemctl daemon-reload`) so it is totally clear what to do here.

**Comment by clintjedwards** [comment]
Hey! Thanks for the suggestions! I agree with these on all fronts. I'll keep this open and try to work them in when I have time, but if you wanna send over a pull request that would be great also.
